namespace Common
{
    public enum FACE
    {
        None = -1,
        Shanghai = 0,
        Alice,
        Mama,
        Mari,
        Marisa,
        DrMorichika,
        Remilia,
        Sakuya,
        Rika,
        TankMan,
        Kumako,                 // Teacher
        Kumami,                 // Chip Shop owner
        MsAsakura,              // Lab Teacher
        Patchouli,              // Kumami's Navi
        Reisen,
        Yorihime,
        NaviGreenRobot = 16,
        NaviOrangeMale,
        NaviBlueRobot,
        NaviPinkFemale,
        NaviChild,
        Sprite,
        NaviPurplePunk,
        NaviPurpleHeel,
        NaviPurpleFemale,
        MsKoaNavi,              // Kumako Koa's Navi
        NaviPurpleChild,
        NaviBlackHeel,
        NaviBlackRobe,
        BrokenSprite,
        KikuriHuman,
        KikuriCombat,
        MaleChild = 32,
        FemaleChild,
        MaleStudent,
        FemaleStudent,
        MaleAdult,
        FemaleAdult,
        MaleOld,
        FemaleOld,
        MaleElderly,
        FemaleElderly,
        Scientist,
        Punk,
        FemaleMiddleAged,
        Nurse,
        Policeman,
        Sheet3Face16Blank,
        CirnoOpFaceHidden = 48,
        CirnoOpFaceShownLetty,
        Cirno,
        Medicine,
        PyroManOpMokou,
        PyroMan,
        Murasa,
        ScissorManOpTarakhan,
        ScissorMan,
        Sheet4Face9Blank,
        GoldRobot,              // Border Concern Shikigami Good?
        BlackRobot,             // Border Concern Shikigami Bad?
        SoundOnly,
        HoodedFace,
        DruidMan,
        MsAsakuraEvil,
        PresidentYukari = 64,
        Yamame,
        SanaeReporter,
        TsubakiNekku,
        SpannerMan,
        Tenshi,
        Iku,
        Troid,
        YoungAlice,
        MsKamishirasawa,        // Eien Teacher HakutakuMan Op
        Sumireko,               // Eien student, Renko younger sister
        Sagume,                 // Reisen's Handler/Boss
        Reimu,                  // Shrine kid TortoiseMan Op
        TortoiseMan,
        MsFamous,
        Sheet5Face16Blank,
        NaviOrangeRobot = 80,
        Autoroid,
        NaviBlueRobot2,
        NaviGreenFemale,
        NaviChild2,
        NaviRedSprite,
        Henchie,
        NaviPurpleHeel2,
        NaviPurpleFemale2,
        MsAsakuraNavi,          // Ms Asakura's Navi
        Ran,                    // PresidentYukari's Navi1, Maribel's Navi
        Chen,                   // PresidentYukari's Navi2
        FlandreNormal,
        FlandreAngry,
        FlandreEvil,
        Sheet6Face16Blank,
        MaleGlassesStudent = 96,
        BlackHairFemaleStudent,
        BrownHairMaleStudent,
        BlondeHairGalStudent,
        BrownHairGalStudent,
        Sheet7Face6Blank,
        Sheet7Face7Blank,
        Sheet7Face8Blank,
        Sheet7Face9Blank,
        Sheet7Face10Blank,
        Sheet7Face11Blank,
        Sheet7Face12Blank,
        Sheet7Face13Blank,
        Sheet7Face14Blank,
        Sheet7Face15Blank,
        Sheet7Face16Blank,
        HakuTakuMan = 112,
        Renko,                  // RenkoSis board, Sumireko's older sister, Maribel's friend, N1 league
        Eirin,                  // Doctor, Reisen's adopted mother, EirinCall
        Koishi,                 // Satori's younger sister, Utsuho's Op
        Satori,                 // Sick blind girl, Koishi's older sister, Rin's Op
        SatoriSeeing,           // Satori, after eyesight restored
        Rin,                    // Satori's Navi
        Utsuho,                 // Koishi's Navi (chibi?)
        WriggleHat,
        BeetleMan,
        WriggleCrown,
        YuukaKazami,            // Florist
        Yumeko,                 // Sprite turned Navi
        UtsuhoDark,             // Utsuho corrupted by DarkChip
        Maribel,                // PresidentYukari's niece, Border Concern replacement president, Ran Op
        Sheet8Face16Blank,
        OrangeHairMaleWesterner = 128,
        GreenHairFemalePinkEyes,
        BlondHairMaleChild,
        OrangeHairFemaleChild,
        WhiteHairMaleButler,
        WhiteHairFemaleRichLady,
        BlackHairMaleBlackRapper,
        Sheet9Face8Blank,
        Sheet9Face9Blank,
        Sheet9Face10Blank,
        Sheet9Face11Blank,
        Sheet9Face12Blank,
        Sheet9Face13Blank,
        Sheet9Face14Blank,
        Sheet9Face15Blank,
        Sheet9Face16Blank,
        Youmu = 144,
        FlandreHidden,
        YuyukoCasual,
        YuyukoCombat,
        Mima,
        SageGlowing,
        Ghost,
        Sheet10Face8Blank,
        Sheet10Face9Blank,
        Sheet10Face10Blank,
        Sheet10Face11Blank,
        Sheet10Face12Blank,
        Sheet10Face13Blank,
        Sheet10Face14Blank,
        Sheet10Face15Blank,
        Sheet10Face16Blank
    }
}
